export const SET_MARK  = 'SET_MARK'
export const SET_MARK_SUCCESS  = 'SET_MARK_SUCCESS'
export const SET_MARK_FAILED = 'SET_MARK_FAILED'

export const GET_MARK  = 'GET_MARK'
export const GET_MARK_SUCCESS  = 'GET_MARK_SUCCESS'
export const GET_MARK_FAILED = 'GET_MARK_FAILED'

export const DELETE_PHOTO  = 'DELETE_PHOTO'
export const DELETE_PHOTO_SUCCESS  = 'DELETE_PHOTO_SUCCESS'
export const DELETE_PHOTO_FAILED = 'DELETE_PHOTO_FAILED'


